name: lectoplay
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # LOCAL
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5

  # FIREBASE
  firebase_core: ^4.7.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.0.0

  # IMÁGENES
  image_picker: ^1.1.2

  # AUDIO
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"